#!/bin/bash
clear

pkg install root-repo -y
pkg install x11-repo -y
pkg install tur-repo -y
pkg install wget -y
pkg install git -y
pkg install hashdeep -y
pkg install termux-am -y
pkg install termux-x11-nightly -y
pkg install p7zip -y
pkg install patchelf -y
pkg install ncurses-utils -y
pkg install mesa-zink -y
pkg install virglrenderer-mesa-zink -y
pkg install vulkan-loader-android -y
pkg install android-tools -y
pkg install python-tkinter -y
pkg install xfce4 -y
apt install xfce4-whiskermenu-plugin -y
apt install xfce4-screenshooter -y
apt install xfce4-taskmanager -y
apt install xfce4-docklike-plugin -y
apt install matchbox-keyboard -y
pkg install gimp -y
pkg install mpv -y
pkg install firefox -y
pkg install vlc -y
pkg install vlc-qt -y
pkg install abiword -y
apt install ristretto -y
pkg update -y
pkg upgrade -y
apt-get clean -y
apt-get update -y
apt-get upgrade -y
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade
clear

if [ -d "$PREFIX/glibc" ]; then
    echo "Glibc found."
else
    echo "Glibc not found."
fi

echo ""
echo "Select an option:"
echo "1) Install Box86 version"
echo "2) Install WoW64 version"
echo -n "Selected number: "
read choice

case "$choice" in
1)
    wget -q --show-progress -O /data/data/com.termux/files/usr/mobox-box86-glibc-xfce.tar.xz "https://github.com/Shephard225/Mobox-XFCE/releases/download/Glibc/mobox-box86-glibc-xfce.tar.xz"
    tar -xf /data/data/com.termux/files/usr/mobox-box86-glibc-xfce.tar.xz -C /data/data/com.termux/files/usr/
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce /data/data/com.termux/files/usr/bin/mobox-xfce
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce --unistall /data/data/com.termux/files/usr/bin/mobox-xfce-unistall
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-update /data/data/com.termux/files/usr/bin/mobox-xfce-update
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce --unistall
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-update
    echo "Box86 version installed successfully."
    ;;
2)
    wget -q --show-progress -O /data/data/com.termux/files/usr/mobox-wow64-glibc-xfce.tar.xz "https://github.com/Shephard225/Mobox-XFCE/releases/download/Glibc/mobox-wow64-glibc-xfce.tar.xz"
    tar -xf /data/data/com.termux/files/usr/mobox-wow64-glibc-xfce.tar.xz -C /data/data/com.termux/files/usr/
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce /data/data/com.termux/files/usr/bin/mobox-xfce
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-unistall /data/data/com.termux/files/usr/bin/mobox-xfce-unistall
    ln -sf /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-update /data/data/com.termux/files/usr/bin/mobox-xfce-update
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-unistall
    chmod +x /data/data/com.termux/files/usr/glibc/opt/scripts/mobox-xfce-update
    echo "WoW64 version installed successfully."
    ;;
*)
    echo "Invalid option."
    exit 1
    ;;
esac

echo "To start type: mobox-xfce"
